#config_version=6
mode:
  start_events: charleston_win_start
  stop_events: timer_quit_charleston_win_time_complete
  restart_on_next_ball: false
  priority: 300

###########################

event_player:
  timer_quit_charleston_win_time_complete: twenties_start

###########################

show_player:
  mode_charleston_win_started:
    charleston_win_show:
      speed: 15
      loops: -1
      priority: 100
    charleston_win_show_2:
      speed: 10
      loops: -1
      priority: 100

###########################

slide_player:
  mode_charleston_win_started: charleston_win_slide

###########################

slides:
  charleston_win_slide: []

###########################

widgets:
  charleston_win_banner:
    type: text
    text: YOU DANCE ALL NIGHT !
    color: FF8000
    y: 28%
    x: 50%
    z: 100
    expire: 10s
    animations:
        add_to_slide:                   
        - property: opacity         
          value: 1                  
          duration: .5s             
        - property: opacity         
          value: 0
          duration: .5s
          repeat: true

  charleston_win_banner_2:
    type: text
    text: 175,000 points !
    color: FF8000
    y: 65%
    x: 50%
    z: 100
    expire: 10s
    animations:
        add_to_slide:                   
        - property: opacity         
          value: 1                  
          duration: .5s             
        - property: opacity         
          value: 0
          duration: .5s
          repeat: true  

  video_charleston_win_scratch_widget:
    type: video
    video: scratch_movie
    auto_play: True
    end_behavior: loop
    z: 2

###########################

widget_player:
  mode_charleston_win_started:
    charleston_win_banner, charleston_win_banner_2, video_charleston_win_scratch_widget, base_without_score_widget, superpops_widget, base_frame_widget:
      action: add
      slide: charleston_win_slide

###########################

variable_player:
  mode_charleston_win_started:
    mission_charleston:
      action: set
      string: 'completed'

    score: 175000
    charleston_champion: 175000

    mission_boost_multiplier:
      action: add
      float: 0.1

###########################

timers:
  quit_charleston_win_time:
    start_value: 10
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_charleston_win_started

###########################

sound_player:
  mode_charleston_win_started:
    applause_win_sound_pool:
      action: play
      loops: 0
      volume: 1
    violin_sound_victory_pool:
      action: play
      loops: 0
      volume: 1
    super_jackpot_voice_pool:
      action: play
      loops: 0
      volume: 2