#config_version=6
mode:
  start_events: aza_win_start
  stop_events: timer_quit_aza_win_time_complete
  restart_on_next_ball: false
  priority: 300

###########################

event_player:
  timer_quit_aza_win_time_complete: twenties_start

###########################

show_player:
  mode_aza_win_started:
    aza_win_show:
      speed: 15
      loops: -1
      priority: 100

###########################

slide_player:
  mode_aza_win_started: aza_win_slide

###########################

slides:
  aza_win_slide: []

###########################

widgets:
  aza_win_banner:
    type: text
    text: YOU SAVED YOURSELF
    color: red
    y: 38%
    x: 50%
    z: 100
    expire: 10s
    animations:
        add_to_slide:                   
        - property: opacity         
          value: 1                  
          duration: .5s             
        - property: opacity         
          value: 0
          duration: .5s
          repeat: true
  aza_win_banner_2:
    type: text
    text: FROM AN ETERNITY OF MADNESS !
    color: red
    y: 28%
    x: 50%
    z: 100
    expire: 10s
    animations:
        add_to_slide:                   
        - property: opacity         
          value: 1                  
          duration: .5s             
        - property: opacity         
          value: 0
          duration: .5s
          repeat: true

  aza_win_banner_3:
    type: text
    text: 100,000 points !
    color: red
    y: 65%
    x: 50%
    z: 100
    expire: 10s
    animations:
        add_to_slide:                   
        - property: opacity         
          value: 1                  
          duration: .5s             
        - property: opacity         
          value: 0
          duration: .5s
          repeat: true  

  video_aza_win_scratch_widget:
    type: video
    video: scratch_movie
    auto_play: True
    end_behavior: loop
    z: 2

###########################

widget_player:
  mode_aza_win_started:
    aza_win_banner, aza_win_banner_2, aza_win_banner_3, video_aza_win_scratch_widget, base_without_score_widget, superpops_widget, cthulhu_frame_image:
      action: add
      slide: aza_win_slide

###########################

variable_player:
  mode_aza_win_started:
    azathoth_mission_available:
      action: set
      string: 'completed'

    score: 100000
    aza_champion: 100000

###########################

timers:
  quit_aza_win_time:
    start_value: 5
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_aza_win_started

###########################

sound_player:
  mode_aza_win_started:
    evil_laugh_pool:
      action: play
      loops: 0
      volume: 2

    super_jackpot_voice_pool:
      action: play
      loops: 0
      volume: 1

    dark_win_sound_pool:
      action: play
      loops: 0
      volume: 1