#config_version=6

mode:
  start_events: stop_mini_wizard_twenties
  stop_events: twenties_start
  priority: 4600
  game_mode: true
  restart_on_next_ball: false

###########################

event_player:
  mode_mini_wizard_twenties_ending_started: flipper_off, slingshot_off
  balldevice_bd_drain_ball_enter: mini_wizard_twenties_ending_ball_held
  timer_mini_wizard_twenties_ending_timer_complete: mini_wizard_twenties_ending_done
  mini_wizard_twenties_ending_done: twenties_start, flipper_on, slingshot_on

###########################

# Retient une seule bille dans bd_drain pendant le timer d'affichage
ball_holds:
  mini_wizard_twenties_ending_hold:
    balls_to_hold: 1
    hold_devices: bd_drain
    enable_events: mode_mini_wizard_twenties_ending_started
    release_one_events: mini_wizard_twenties_ending_done
    disable_events: mini_wizard_twenties_ending_done

###########################

timers:
  mini_wizard_twenties_ending_timer:
    start_value: 10
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mini_wizard_twenties_ending_ball_held

###########################
