#config_version=6
mode:
  start_events: pre_king_start
  stop_events: pre_king_stop, timer_launch_king_time_complete
  priority: 200
  restart_on_next_ball: true

###########################
event_player:
  s_action_active{current_player.great_ones_availability=='ok'}: king_start, pre_king_stop, twenties_stop

###########################

variable_player:
  mode_pre_king_started:
    king_mission_available:
      action: set
      string: 'available'
    random_event_available:
      action: set
      string: 'no'

###########################

slides:
  pre_king_slide:
    - type: text
      text: WANT TO SEE A PLAY ?
      color: yellow
      y: 28%
      x: 50%
      z: 100
      style: mission_text
    - type: text
      text: If you want to fight the King
      color: yellow
      y: 72%
      x: 50%
      z: 100
      style: mission_text_small
    - type: text
      text: push action button !
      color: yellow
      y: 62%
      x: 50%
      z: 100
      style: mission_text_small
    - type: image
      image: mini_king_NB    
      y: 50%
      x: 20%
      z: 100
    - type: Image
      image: frame_cthulhu
      z: 10
    - type: video
      video: mystery_scratch_movie
      auto_play: True
      end_behavior: loop
      z: 3

###########################

slide_player:
  mode_pre_king_started:
    pre_king_slide:
      action: play

###########################

show_player:
  mode_pre_king_started:
    pre_king_blink_show:
      speed: 10

###########################

timers:
  launch_king_time:
    start_value: 7
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_pre_king_started

###########################

sound_player:
  mode_pre_king_started:
    king_ready_voice_pool:
      action: play
      volume: 2

sound_pools:
  king_ready_voice_pool:
    load: on_demand
    type: random
    track: voice
    sounds:
      - king_ready_1
      - king_ready_2
