#config_version=6
mode:
  start_events: pre_cthulhu_start
  stop_events: pre_cthulhu_stop, timer_launch_cthulhu_time_complete
  priority: 200
  restart_on_next_ball: true

###########################

event_player:
  s_action_active{current_player.great_ones_availability=='ok'}: cthulhu_start, pre_cthulhu_stop, twenties_stop

###########################

variable_player:
  mode_pre_cthulhu_started:
    cthulhu_mission_available:
      action: set
      string: 'available'
    random_event_available:
      action: set
      string: 'no'

###########################

slides:
  pre_cthulhu_slide:
    - type: text
      text: CTHULHU RISING !
      color: 00994C
      y: 28%
      x: 50%
      z: 100
      style: mission_text
    - type: text
      text: If you want to fight cthulhu
      color: 00994C
      y: 72%
      x: 50%
      z: 100
      style: mission_text_small
    - type: text
      text: dive into the lower scoop !
      color: 00994C
      y: 62%
      x: 50%
      z: 100
      style: mission_text_small
    - type: image
      image: mini_cthulhu_NB    
      y: 50%
      x: 20%
      z: 100
    - type: Image
      image: frame_cthulhu
      z: 10
    - type: video
      video: mystery_scratch_movie
      auto_play: True
      end_behavior: loop
      z: 3

###########################

slide_player:
  mode_pre_cthulhu_started:
    pre_cthulhu_slide:
      action: play

###########################

show_player:
  mode_pre_cthulhu_started:
    pre_cthulhu_blink_show:
      speed: 10

###########################

timers:
  launch_cthulhu_time:
    start_value: 7
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_pre_cthulhu_started

###########################

sound_player:
  mode_pre_cthulhu_started:
    cthulhu_ready_voice_pool:
      action: play
      volume: 2

sound_pools:
  cthulhu_ready_voice_pool:
    load: on_demand
    type: random
    track: voice
    sounds:
      - cthulhu_ready_1
      - cthulhu_ready_2

