#config_version=6

mode:
  start_events: kickback_activated
  stop_events: kickback_stop, game_ended, ball_ended, game_ending, ball_ending, ball_save_kickback_emergency_save_saving_ball
  priority: 1100
  restart_on_next_ball: false


widgets:
#  kickback_start_banner:
#    type: text
#    text: Kickback activated !
#    color: white
#    y: 30%
#    x: 50%
#    z: 100
#    expire: 5s

  # kickback_banner:
  #   type: text
  #   text: HELP activated
  #   y: top-170
  #   x: right-150
  #   z: 1000
  #   font_size: 50
  #   anchor_x: right
  #   anchor_y: top
  #   animations:
  #       add_to_slide:                   
  #       - property: opacity         
  #         value: 1                  
  #         duration: .5s             
  #       - property: opacity         
  #         value: 0
  #         duration: .5s
  #         repeat: true  

#widget_player:
#  mode_kickback_started:
#    kickback_start_banner:
#      slide: base_slide
#    kickback_banner:
#      slide: base_slide



###########################

show_player:
  mode_kickback_started:
    kickback_save_blink_show:
      speed: 5
      loops: -1
  mode_kickback_stopped:
    kickback_save_blink_show: stop

###########################

event_player:
  kickback_ac_left_kickback_fired: kickback_stop|3s

ball_saves:
  kickback_emergency_save:
    active_time: 4s
    hurry_up_time: 1s
    grace_period: 0s
    enable_events: kickback_ac_left_kickback_fired, s_roll_left_outlane_active
    disable_events: kickback_stop
    auto_launch: true
    balls_to_save: 1

###########################

sound_pools:
  kickback_activated_sound:
    load: preload
    type: random
    track: voice
    sounds:
      - kickback_activated_1
      - kickback_activated_2
      - kickback_activated_3
      - kickback_activated_4
      - kickback_activated_5
      - kickback_activated_6
      - kickback_activated_7
      - kickback_activated_8

sound_player:
  kickback_ac_left_kickback_fired:
    kickback_activated_sound:
      action: play
      volume: 2