#config_version=6
mode:
  start_events: secret_library_start
  stop_events: secret_library_stop, ball_ended
  priority: 600
  restart_on_next_ball: false

###########################

event_player:
  timer_secret_library_end_time_complete: secret_library_stop

###########################

random_event_player:
  mode_secret_library_started:
    events:
      - launch_secret_library_video_1
      - launch_secret_library_video_2

###########################

slides:
  secret_library_slide: []

###########################

slide_player:
  mode_secret_library_started: secret_library_slide

###########################

widgets:
  video_secret_library_1_scratch_widget:
    type: video
    video: secret_library_scratch_movie_1
    auto_play: true
    end_behavior: stop
    z: 5

  video_secret_library_2_scratch_widget:
    type: video
    video: secret_library_scratch_movie_2
    auto_play: true
    end_behavior: stop
    z: 5

###########################

widget_player:
  mode_secret_library_started:
    cthulhu_frame_image, base_score_widget, superpops_widget:
      action: add
      slide: secret_library_slide

  launch_secret_library_video_1:
    video_secret_library_1_scratch_widget:
      slide: secret_library_slide   
  launch_secret_library_video_2:
    video_secret_library_2_scratch_widget:
      slide: secret_library_slide   

###########################

timers:
  secret_library_end_time:
    start_value: 0
    end_value: 5
    direction: up
    tick_interval: 1s
    restart_on_complete: true
    control_events:
      - action: start
        event: mode_secret_library_started

###########################

videos:
  secret_library_scratch_movie_1:
    width: 1440
    height: 900
    file: secret_library_video_1.mp4

  secret_library_scratch_movie_2:
    width: 1440
    height: 900
    file: secret_library_video_2.mp4
